# Generated by Django 4.0.3 on 2022-03-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('primer_nombre', models.CharField(help_text='Introduzca el 1er Nombre', max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, help_text='Introduzca el 2do Nombre', max_length=50)),
                ('primer_apellido', models.CharField(help_text='Introduzca el 1er Apellido', max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, help_text='Introduzca el 2do Apellido', max_length=50)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_de_nacimiento', models.DateField()),
                ('vencimiento_dni', models.DateField()),
                ('vencimiento_registro', models.DateField()),
                ('sector', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Introduzca la Marca', max_length=20)),
                ('modelo', models.CharField(help_text='Introduzca el Modelo', max_length=20)),
                ('dominio', models.CharField(help_text='Introduzca la Patente', max_length=20)),
            ],
        ),
    ]
