# Generated by Django 4.0.3 on 2022-03-29 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Capp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('dni_conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Capp.conductor')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Capp.vehiculo')),
            ],
        ),
    ]
