# Generated by Django 4.0.3 on 2022-03-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capp', '0005_alter_conductor_segundo_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='dni_conductor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='dominio',
            field=models.CharField(max_length=7),
        ),
    ]
